### ISSUE TITLE
StructuredClone is not defined

### ISSUE THREAD

**Issue by elraro** [congatudo/Congatudo#45]
## Describe the bug

```
congatudo  | /snapshot/app/backend/lib/Configuration.js:18
congatudo  |         this.settings = structuredClone(DEFAULT_SETTINGS);
congatudo  |         ^
congatudo  |
congatudo  | ReferenceError: structuredClone is not defined
congatudo  |     at new Configuration (/snapshot/app/backend/lib/Configuration.js:18:9)
congatudo  |     at new Valetudo (/snapshot/app/backend/lib/Valetudo.js:23:23)
congatudo  |     at Object.<anonymous> (/snapshot/app/backend/index.js:6:18)
congatudo  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
congatudo  |     at Module._compile (pkg/prelude/bootstrap.js:1937:32)
congatudo  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
congatudo  |     at Module.load (node:internal/modules/cjs/loader:981:32)
congatudo  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
congatudo  |     at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
congatudo  |     at node:internal/main/run_main_module:17:47
```

## To Reproduce
1. Install Congatudo 2023.02
2. Profit

### Congatudo Version
2023.02

**Comment by elraro** [comment]
Solved https://github.com/congatudo/Congatudo/commit/4cf17a62ca0d32bab2be3bc6bd8d89e8bdf3ed4a
