### ISSUE TITLE
Warning TypeError while reading error ‘severity’

### ISSUE THREAD

**Issue by marcosav** [congatudo/Congatudo#77]
## Describe the bug

```
[2023-05-15T11:24:27.386Z] [WARN] Failed to parse value to be sent for topic valetudo/conga/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:714:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## To Reproduce
1. Move the robot out of the charging dock (State will change from Docked to Idle)
2. Remove the dust deposit (State will change from Idle to Error, and Error will change status to Unknown Error)
3. Now the above warning will show up periodically (~5s).

If dust deposit is put back, status will change to Idle and the warning will stop showing.

### Vacuum Model
Conga 5490

### Congatudo Version
2023.4

Thank you so much!

**Comment by elraro** [comment]
https://github.com/congatudo/Congatudo/commit/16f778c34fc2492b01c811567c1616764f4a406d

Maybe this commit solved this problem. Try tomorrow with the nightly build or the beta addon @marcosav

**Comment by marcosav** [comment]
@elraro Hi!, it seems to be solved, I have tried to reproduce the error, now logs are OK and in the web UI appeared more details about the error.
![IMG_4899](https://github.com/congatudo/Congatudo/assets/10092933/14b519a6-20aa-46db-a831-ba5472b9acf0)


In HA seems great too.
![IMG_4900](https://github.com/congatudo/Congatudo/assets/10092933/d158d994-a90e-442f-ae68-09ffc8b68fb2)


Thank you very much!
