### ISSUE TITLE
Congatudo display unknown error in banner

### ISSUE THREAD

**Issue by Nismonx** [congatudo/Congatudo#84]
## Describe the bug
 After update 0.2.5 - 2022-10-21 congatudo is no longer parce messages correctly from conga 4090.

## To Reproduce
 1Remove dust bin: should display 'an error occured: dustbin not exist' but instead get 'an unknown error occurred'.
2Turn conga upside-down should display 'an error occurred: wheels up' but yet again it shows unknown error.
I'm sure there are other error or messages not parse correctly, those are just the ones I've experienced.
### Screenshots

![Screenshot_20230905_093842_Telegram](https://github.com/congatudo/Congatudo/assets/62077532/0f67c627-5c74-460b-89a4-8f1c4995efb7)

Old version of congatudo:

![Screenshot_20230905_095130_Telegram](https://github.com/congatudo/Congatudo/assets/62077532/6e768faf-5dbd-41e4-8dd6-7fdc6704fb30)
![Screenshot_20230905_095152_Telegram](https://github.com/congatudo/Congatudo/assets/62077532/1b5b109e-75fc-4268-9913-1dc5171822a2)
![Screenshot_20230905_095807_Telegram](https://github.com/congatudo/Congatudo/assets/62077532/792e80a7-efd8-41f3-9cfc-27ca7fd99d3f)

### Vacuum Model

Conga 4090

## Additional context

I don't know if this is relevant but it's all it shows in the log from Congatudo add-on:
```
2023-08-28T09:53:18.245Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Nismonx** [comment]
Relate to issue #77 

Only just noticed that 😳 

Thanks everyone...

**Comment by elraro** [comment]
This release is really old. Could you update please?

**Comment by Nismonx** [comment]
Congatudo 2023.05 May 22 release? 
I have tried it and get the errors.

That's why I had to revert all the way back to 0.2.4

![Screenshot_20231015_163551_Home Assistant](https://github.com/congatudo/Congatudo/assets/62077532/cf480414-c533-40b1-b9f4-42ec7a916a2d)

**Comment by Nismonx** [comment]
I will update to the latest release again and restarting  HA and Conga4090.

I'll report back soon 👍

**Comment by elraro** [comment]
Ok, understood. Please, try again, and provide logs from the container or the Log section from Congatudo, not screenshots.

Thank you!

**Comment by Nismonx** [comment]
So far so good:

2023-10-15T15:43:19.208Z
Info
Set Logfile to /tmp/valetudo.log
2023-10-15T15:43:19.230Z
Info
Starting Valetudo 2023.05
2023-10-15T15:43:19.232Z
Info
Commit ID: 093d853701a06a4d07aa494c7b84650cb9ea2f3e
2023-10-15T15:43:19.233Z
Info
Configuration file: /config/valetudo.json
2023-10-15T15:43:19.234Z
Info
Logfile: /tmp/valetudo.log
2023-10-15T15:43:19.235Z
Info
Robot: Cecotec Conga (CecotecCongaRobot)
2023-10-15T15:43:19.235Z
Info
JS Runtime Version: v18.12.1-Valetudo
2023-10-15T15:43:19.236Z
Info
Arch: arm64
2023-10-15T15:43:19.238Z
Info
Max Heap Size: 64 MiB
2023-10-15T15:43:19.238Z
Info
Node Flags: --expose-gc --max-heap-size=64
2023-10-15T15:43:19.247Z
Info
Autogenerated System ID: FairWindingDuck
2023-10-15T15:43:23.874Z
Info
Webserver running on port 8080
2023-10-15T15:43:24.324Z
Info
Connected successfully to MQTT broker
2023-10-15T15:43:24.760Z
Info
MQTT configured
2023-10-15T15:43:25.886Z
Info
Added new robot with id '8136'


I'll just need restart everything....

**Comment by Nismonx** [comment]
OK, so after restarting both,

I have this (the 3 last error are normal I think)

`2023-10-15T15:43:19.208Z
Info
Set Logfile to /tmp/valetudo.log
2023-10-15T15:43:19.230Z
Info
Starting Valetudo 2023.05
2023-10-15T15:43:19.232Z
Info
Commit ID: 093d853701a06a4d07aa494c7b84650cb9ea2f3e
2023-10-15T15:43:19.233Z
Info
Configuration file: /config/valetudo.json
2023-10-15T15:43:19.234Z
Info
Logfile: /tmp/valetudo.log
2023-10-15T15:43:19.235Z
Info
Robot: Cecotec Conga (CecotecCongaRobot)
2023-10-15T15:43:19.235Z
Info
JS Runtime Version: v18.12.1-Valetudo
2023-10-15T15:43:19.236Z
Info
Arch: arm64
2023-10-15T15:43:19.238Z
Info
Max Heap Size: 64 MiB
2023-10-15T15:43:19.238Z
Info
Node Flags: --expose-gc --max-heap-size=64
2023-10-15T15:43:19.247Z
Info
Autogenerated System ID: FairWindingDuck
2023-10-15T15:43:23.874Z
Info
Webserver running on port 8080
2023-10-15T15:43:24.324Z
Info
Connected successfully to MQTT broker
2023-10-15T15:43:24.760Z
Info
MQTT configured
2023-10-15T15:43:25.886Z
Info
Added new robot with id '8136'
2023-10-15T15:49:00.182Z
Error
Failed auto refresh: DomainException: Timeout waiting for response from opcode 'DEVICE_MAPID_GET_CONSUMABLES_PARAM_RSP'
    at Timeout.fail [as _onTimeout] (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1024:16)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  metadata: undefined
}
2023-10-15T15:49:08.502Z
Error
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
2023-10-15T15:49:09.625Z
Error
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}`

I then remove the dustbin to simulate a message and get this instead:
![Screenshot_20231015_165912_Home Assistant](https://github.com/congatudo/Congatudo/assets/62077532/8b85c99c-3f8c-47e4-ae73-d8225359ae16)

From the conga log:
`2023-10-15T15:55:48.682Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-15T15:55:49.131Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-15T15:55:49.666Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-15T15:55:49.715Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-15T15:55:49.718Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-15T15:55:51.673Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-15T15:55:53.497Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-15T15:55:55.421Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)
2023-10-15T15:55:56.149Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RobotMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:13)
    at async RobotMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/RobotMqttHandle.js:153:9)
2023-10-15T15:55:59.149Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-15T15:56:00.668Z
Warn
Failed to parse value to be sent for topic valetudo/MeagerCreamyRail/StatusStateAttribute/error: TypeError: Cannot read properties of undefined (reading 'severity')
    at PropertyMqttHandle.getter (/snapshot/app/backend/lib/mqtt/status/StatusStateMqttHandle.js:115:41)
    at PropertyMqttHandle.get (/snapshot/app/backend/lib/mqtt/handles/PropertyMqttHandle.js:104:21)
    at PropertyMqttHandle.getHomie (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:298:53)
    at MqttController.refresh (/snapshot/app/backend/lib/mqtt/MqttController.js:716:36)
    at PropertyMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:237:31)
    at StatusStateMqttHandle.refresh (/snapshot/app/backend/lib/mqtt/handles/MqttHandle.js:240:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by elraro** [comment]
This seems
